{
 "title": "Business",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producing Rate  - Wikipedia changes / 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(reactor_onNext_delay_seconds_count{flow=\"recentchange\"}[1m])",
     "legendFormat": "changes"
    }
   ]
  },
  {
   "title": "Consuming Rate  - Wikipedia changes / 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(reactor_requested_requested_amount_sum{flow=\"recentchange\"}[1m])",
     "legendFormat": "changes"
    }
   ]
  },
  {
   "title": "Processing errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(reactor_flow_duration_seconds_count{flow=\"processing\",status=\"error\"}[1m])",
     "legendFormat": "{{exception}}"
    }
   ]
  }
 ]
}