{
 "title": "Schedulers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Threads per scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(executor_pool_size_threads) by (reactor_scheduler_id)",
     "legendFormat": "{{reactor_scheduler_id}}"
    },
    { "expr": "jvm_threads_live_threads", "legendFormat": "total threads" }
   ]
  },
  {
   "title": "completed tasks / 1min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reactor_scheduler_id)(irate(executor_completed_tasks_total[1m]))",
     "legendFormat": "completed by {{reactor_scheduler_id}}"
    },
    {
     "expr": "sum by (reactor_scheduler_id)(irate(executor_queued_tasks[1m]))",
     "legendFormat": "queued in {{reactor_scheduler_id}}"
    }
   ]
  },
  {
   "title": "Task execution latency",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(executor_seconds_max * 1000) by (reactor_scheduler_id)",
     "legendFormat": "{{reactor_scheduler_id}}"
    }
   ]
  },
  {
   "title": "Queued tasks",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(executor_queued_tasks >= 0) by (reactor_scheduler_id)",
     "legendFormat": "{{reactor_scheduler_id}}"
    }
   ]
  }
 ]
}